# Main Application Configuration
# Activate profile using: -Dspring.profiles.active=dev or -Dspring.profiles.active=prod
# Default profile is 'dev'

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Common Configuration
spring.application.name=InventoryMgtSystem

